# Generated by Django 3.0.7 on 2020-06-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200607_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='display_number',
            new_name='display_order',
        ),
    ]
