# Generated by Django 3.0.7 on 2020-06-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200607_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
